openapi: 3.0.2

info:
  title: hrchat
  version: 0.1.0

tags:
  - name: auth
    description: "Auth namespace"
  - name: users
    description: "Users namespace"
  - name: students
    description: "Students namespace"
  - name: rooms
    description: "Rooms namespace"

paths:
  "/api/auth/trainer/":
    post:
      tags:
        - auth
        - users
        - trainers
      summary: "Login trainer"
      requestBody:
        $ref: "#/components/requestBodies/RegistrationRequestBodyTrainer"
      responses:
        "200":
          $ref: "#/components/responses/TokenObtain200"
        "400":
          $ref: "#/components/responses/TokenObtain400"

  "/api/auth/student/":
    post:
      tags:
        - auth
        - users
        - students
      summary: "Registration or login student"
      requestBody:
        $ref: "#/components/requestBodies/RegistrationRequestBodyStudent"
      responses:
        "200":
          $ref: "#/components/responses/TokenObtain200"
        "400":
          $ref: "#/components/responses/TokenObtain400"

  "/api/auth/token/refresh/":
    post:
      tags:
        - auth
      summary: "Refresh token"
      requestBody:
        $ref: "#/components/requestBodies/TokenRefreshRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/TokenRefresh200"
        "400":
          $ref: "#/components/responses/TokenRefresh400"

  "/api/trainings/rooms/":
    post:
      tags:
        - rooms
      summary: "Create room"
      security:
        - bearerAuth: []
      requestBody:
        $ref: "#/components/requestBodies/RoomCreateBody"
      responses:
        "201":
          $ref: "#/components/responses/RoomCreate201"
        "400":
          $ref: "#/components/responses/RoomCreate400"

  "/api/trainings/results/{room_uuid}/":
    get:
      tags:
        - rooms
      summary: "Get result by room"
      parameters:
        - name: room_uuid
          in: path
          schema:
            type: string
            format: uuid
          required: true
      security:
        - bearerAuth: []
      responses:
        "200":
          $ref: "#/components/responses/XLSXFile"
        "401":
          description: "Unauthhorized"
        "404":
          description: "Not Found"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserBase:
      type: object
      properties:
        email:
          type: string
          format: email
        full_name:
          type: string
        is_trainer:
          type: boolean
        password:
          type: string

    StudentBase:
      type: object
      properties:
        is_ready:
          type: boolean
        room:
          $ref: "#/components/schemas/RoomBase"
        points:
          type: number
        user:
          $ref: "#/components/schemas/UserBase"

    RoomBase:
      type: object
      properties:
        id:
          type: string
          format: uuid
        count_students:
          type: number
        count_rounds:
          type: number
        duration_round:
          type: number

  requestBodies:
    RegistrationRequestBodyTrainer:
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      required: true

    RegistrationRequestBodyStudent:
      content:
        application/json:
          schema:
            type: object
            properties:
              full_name:
                type: string
              uuid:
                type: string
      required: true

    TokenObtainRequestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: string
                format: email
              password:
                type: string
      required: true

    TokenRefreshRequestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              refresh:
                type: string
      required: true

    RoomCreateBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              count_students:
                type: number
              count_rounds:
                type: number
              duration_round:
                type: number

  responses:
    XLSXFile:
      content:
        application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
          schema:
            type: string
            format: binary
      required: true

    RegistrationTrainer201:
      description: "Created"
      content:
        application/json:
          schema:
            type: object
            properties:
              access:
                type: string
                description: "access token"
              refresh:
                type: string
                description: "refresh token"

    RegistrationTrainer400:
      description: "Bad Request"

    RegistrationStudent201:
      description: "Created"
      content:
        application/json:
          schema:
            type: object
            properties:
              access:
                type: string
                description: "access token"
              refresh:
                type: string
                description: "refresh token"

    RegistrationStudent400:
      description: "Bad Request"

    TokenObtain200:
      description: "Success"
      content:
        application/json:
          schema:
            type: object
            properties:
              access:
                type: string
                description: "access token"
              refresh:
                type: string
                description: "refresh token"

    TokenObtain400:
      description: "Bad request"
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "No active account found with the given credentials"

    TokenRefresh200:
      description: "Success"
      content:
        application/json:
          schema:
            type: object
            properties:
              access:
                type: string
                description: "access token"
              refresh:
                type: string
                description: "refresh token"

    TokenRefresh400:
      description: "Bad request"
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "Token is invalid or expired"
              code:
                type: string
                example: "token_not_valid"

    RoomCreate201:
      description: "Created"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RoomBase"

    RoomCreate400:
      description: "Bad Request"
      content:
        application/json:
          schema:
            type: object
            properties:
              count_students:
                type: array
                items:
                  type: string
                  example: "Минимальное количество участнков в группе - 2, максимальное - 15"
              trainer:
                type: array
                items:
                  type: string
                  example: "Not Found"

    RoomRetrieve:
      description: "Room info"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RoomBase"

    StudentRetrieve:
      description: "Student info"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StudentBase"
